### ISSUE TITLE
Push latest master version 1.1.3 to clojars

### ISSUE THREAD

**Issue by mangolas** [thebusby/iota#6]

**Comment by thebusby** [comment]
Should have this done within 24 hours. My apologies at the delays to releasing your great work, other issues have been keeping me quite occupied.

**Comment by mangolas** [comment]
Thank you!

**Comment by thebusby** [comment]
https://clojars.org/iota updated.

**Comment by mangolas** [comment]
Thank you, most appreciated. I will look into enhancing the README reflecting the new features some time in the future.
